# Generic
n_folds: 5
num_classes: 36
device: 'cuda'
sample_rate: 16000

# Spectrogram
n_mels: 128
hop_length: 128
n_fft: 512
top_db: 80.0

# Training
batch_size: 32
epochs: 50
learning_rate: 0.0001
num_workers: 4
